INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES
(1, 1, 'Fatburger Davie', 'Although the staff were excellent the burger was not! If I am spending $18 dollars on a burger I expect it to be a good burger. This burger was cold,no flavor and the bun was soggy. In the past I have enjoyed Fatburger but after this experience I will never be back! Much cheaper and better burgers at White Spot.', 'https://lh5.googleusercontent.com/p/AF1QipP9KrohXTvnSrTQbiW9po0afYMmSws0BeZ30WJq=w408-h272-k-no', 49.280390, -123.110680),
(1, 1, 'White Spot Dunsmuir', 'Excellent White Spot restaurant! We were served in a friendly manner and were able to order quickly and then got our food in no time. Atmosphere is warm and friendly, and it is nice that the TVs are conveniently located so no matter where you sit you can see one. Theres lots of seating, and several big booths. The only thing I would say is that I ordered a Legendary Burger, but wasnt asked if I wanted lettuce and tomato but I didnt realize it, and when I got my order I didnt know for a second what it was. But thats my only complaint, this restaurant really is great and I would definitely recommend it!', 'https://lh5.googleusercontent.com/p/AF1QipN0UiG687fSraEgjcL3vYX8tu04HrjIk5Cs0qZc=w408-h306-k-no', 49.281980, -123.113980),
(1, 1, 'Five Guys', 'I went to this place with my husband and we had a great time here! The employees were very swift and efficient! We did not have to wait long in spite of the place being crowded! The quality of their burger is top notch! And everything inside of it went amazingly together! The peanuts were an added bonus! The bathrooms were clean and hygienic! The place itself needs some tidying though.', 'https://lh5.googleusercontent.com/p/AF1QipPm9IYsFXBxMJmjSDnJl3KNEidkz2eTNApjZPQ=w408-h306-k-no', 49.281060, -123.119020),
(1, 2, 'MeeT in Gastown', 'As a Thai, from LA.  This place is legit!! Everything is really good here.  Taste super authentic.  "Very spicy" here is actually spicy, which is hard to find.  Even the drinks and desserts were great.  Nothing really to complain. We came in on Christmas day during lunch, the place was packed.  The food was a little slow, but it was worth the wait. Definitely be coming here every time I come to Vegas.', 'https://lh5.googleusercontent.com/p/AF1QipOjE2RwNzKXLUV04l1olFNBxRr5vIaUSwWA_FfD=w408-h272-k-no', 49.283126, -123.104998),
(1, 2, 'Tera V Burger', 'Probably had their No Bull burger in the different variations probably more than 10 times already in the past few years. Usually on delivery and always with a smoothie. I would say I prefer it to meat burgers as a person that does eat meat. Better than Beyond Meat patties in general, but even the beyond meat burgers are prepared better than other places Ive tried. Keep at it guys!', 'https://lh5.googleusercontent.com/p/AF1QipMS1x_9Eitc8KP1T0sCB3Sn8B9bSdaxzIv2PzXZ=w426-h240-k-no', 49.264274, -123.171735),
(1, 2, 'Campagnolo', 'Northern Italian menu, with pizza & housemade salumi, served under exposed bulbs.', 'https://images.squarespace-cdn.com/content/v1/58eda1fcc534a5e94d713978/1521604810164-O8D7HHN7BV9GCY17VM01/ke17ZwdGBToddI8pDm48kAFe3081NhNr2t9KEWiap3J7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmvchaurtRArZJfSwNtuHUKiaLhdcjAPjMR3zMp3I7ofkUS6FEqR4U86UhMLLsVopb/20180208_203420.png?format=1500w', 49.285641, -123.126411),
(1, 2, 'Alibi Room', 'Heritage building with 50 taps of local & imported craft beers, plus a menu of locally sourced food.', 'https://img1.10bestmedia.com/Images/Photos/36218/p-alibi-room-vancouver-bc-canada-nightlife-search-all-nightlife-bar-dance-club-608481_54_990x660_201405311540.jpg', 49.281332299999995, -123.11451249999999),
(1, 2, 'Wakwak Burger', 'Beef burgers with standard & Japanese variations, served with fries & soft drinks through a window.', 'https://pbs.twimg.com/media/CnTAayfUMAAgSwp.jpg', 49.2843797, -123.11493),
(1, 2, 'Relish Gourmet Burgers', 'Fries well done, crispy and not greasy.', 'https://s3-media0.fl.yelpcdn.com/bphoto/ORIpp6mzxGqd6P84wb2LHg/l.jpg', 49.2680316, -123.1115966),
(1, 2, 'Roxy Burger', 'Lively locale offering creative burgers, other pub grub & nightly drink specials.', 'https://ssmscdn.yp.ca/image/resize/1f1bc05c-b66e-4343-8a7a-ed18055c6ca1/ypui-d-mp-pic-gal-lg/roxy-burger-4.jpg', 49.2833213, -123.1165826),
(1, 2, 'The Templeton', 'Jukebox-lined eatery with free-run eggs & breakfast faves, plus organic burgers & classic shakes.', 'https://lh3.googleusercontent.com/proxy/F-Sb0qnDC6ADG7DY5SWbyMk23_L96kSMYql2VBvHUt8mivg23S0eb8luxtr3RTikI8iJXAaejQRwvNT-rAs6h0ernjA6PzdXoPsCWK92yJCs-p8MUssIk5XN', 49.2399548, -123.1394088),
(1, 2, 'Red Robin', 'Chain for gourmet burgers & boozy shakes, with other American comfort fare.', 'https://media-cdn.tripadvisor.com/media/photo-s/03/da/b3/ab/red-robin-gourmet-burgers.jpg', 49.284239, -123.125749);

INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES
(2, 2, 'Devonian Harbour Park', 'After doing a boat tour of the Vancouver Harbour by the paddle boat of Harbour Cruises we decided to relax for a while. We found this nice little park with benches just outside the entrance gate of the Harbour Cruises dock. There were some trees and a lawn and we sat down on a bench in the shade and ate our picnic lunch which we had brought with us. Being very close to Stanley Park and the Seawall walk, which is an extension from the Coal Harbour seawalk trail, we saw a lot of people hiking or biking along to Stanley Park and back. There were good views of the Coal Harbour section with the ships sailing in and out. We enjoyed our brief moments of relaxation and refreshments sitting in Devonian Park.', 'https://lh5.googleusercontent.com/p/AF1QipMyxilaDktSEQMqRDlB2NNnTpfcd1mdy4vdHaNX=w408-h306-k-no', 49.294330, -123.134781),
(2, 2, 'Stanley Park Small Dog Park', 'Great small dog park! My only complaint is that its not that busy, so you dont usually run into other dogs.', 'https://lh5.googleusercontent.com/p/AF1QipPL9PK2XmPx6NKW57vfc1YDQLmmdBX-arsfvcmJ=w408-h766-k-no', 49.292597, -123.144854),
(2, 4, 'Charleson Dog Park', 'Excellent off leash dog park exhisting of a large open field and water feature to the south. 4 stars since it gets very boggy and muddy when the weather is poor.', 'https://lh5.googleusercontent.com/p/AF1QipMjZm2tCLFloeBR6mzeSeXTxOIC60nbpn_tKXDx=w408-h304-k-no', 49.267013, -123.124548),
(2, 4, 'Queen Elizabeth Dog Park', ' I love this park as just a simple place to let the little ones run free. It is off leash right from the parking lot.', 'https://cdn.shopify.com/s/files/1/2537/7848/t/3/assets/nu_dogpark_9_qe.jpg', 49.24966, -123.11934),
(2, 4, 'Hadden Park Dog Beach', 'One of my favourite places in the city. Love watching all the dogs enjoy the beach. ', 'https://vancouver.ca/images/parkfinder/hadden04.jpg', 49.2759755, -123.1461918),
(2, 4, 'Nelson Park Dog Park', 'One of the west ends busiest off leach dogparks. The owners. The lovers. The aunts . The uncles. The dog walkers. ', 'https://www.bringfido.com/assets/images/categories/attraction_parks.jpg', 49.283815, -123.130657),
(2, 4, 'Hinge Park', 'Hinge Park is a naturalized wetland park in the city of Vancouver, British Columbia. Hinge Park covers 2.3 acres and also connects to Habitat Island which covers around 1.5 acres. ', 'https://www.vanwoof.ca/Content/Images/DogParkImages/9/FalseCreek-2.jpg', 49.271795, -123.106561),
(2, 4, 'Trout Lake', 'Great paths for running, walking and cycling. Always cleared. Good time for all.', 'https://s3-media0.fl.yelpcdn.com/bphoto/ZCuT4xbQPiYVUTBfVVRE0A/348s.jpg', 49.258332, -123.061924),
(2, 4, 'Coopers Park', 'Green space on an old sawmill & cooperage plot with a skate park, playground & basketball court.', 'https://www.vanwoof.ca/Content/Images/DogParkImages/11/Coopers-3.jpg', 49.273885, -123.116088),
(2, 4, 'Kings Mill Walk Park', 'Great dog park for pets and humans!  Fenced area right alongside the Spirit Trail which connects to Lonsdale Quay to the east or West Vancouver in the opposite direction. ', 'https://s3-media0.fl.yelpcdn.com/bphoto/YcZ5fghz20VeC_AoDweuWw/o.jpg', 49.3165176,-123.1016717);


INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES
(3, 3, 'Quarry Rock', 'One of the most amazing places I’ve been for hiking! The view and the breeze from the top is mesmerizing. This place is a definite go to In You visit Canada! One of the greatest tourist attraction sites. It is dog friendly too. Saw many people bringing their pets. You can watch the view all day long!', 'https://lh5.googleusercontent.com/p/AF1QipOBm5GnhZGx9ro5dFj-71agwpf1QvweGlCgIlOh=w408-h272-k-no', 49.333827, -122.936710),
(3, 3, 'Buntzen Lake', 'Did this trail on February 18th, very icy! Would recommend spikes or waiting until the snow melts. The trail took us much longer with the ice. Still a nice trail, would be a good easy hike in the warmer months.', 'https://lh5.googleusercontent.com/p/AF1QipNmNxQlC8qKE4AllS6Aws4D2RT85M64-QLqwzcz=w426-h240-k-no', 49.339885, -122.855694),
(3, 1, 'Jug Island Beach', 'Great little hike. At the end you come to a little private beach. One of my favorite hikes. About a 45min to 1 hour hike one way. 2 hours approx to the end and back.', 'https://lh5.googleusercontent.com/p/AF1QipMzkeBMJWRGQwP8YqUFHv1Hk6LIH6W01n4aqalI=w408-h272-k-no', 49.329815, -122.915529),
(3, 5, 'Burnaby Mountain Conservation Area', 'Another our go-to place to walk and hike on Saturday morning. Although we’ve been here so many times but every visit gave us a different vibe. Nice cardio workout or to just enjoy the city view.', 'https://lh5.googleusercontent.com/p/AF1QipMEHtSVdJOLICvJtKiNz81L5jCl6L3nirnSNUVO=w426-h240-k-no', 49.282065, -122.935195),
(3, 5, 'Pacific Spirit Regional Park', 'Pacific Spirit Regional Park is a 874 hectares park located in the University Endowment Lands, on Point Grey to the west of the city of Vancouver, British Columbia.', 'https://www.vancouvertrails.com/images/photos/pacific-spirit-regional-park-3.jpg', 49.273494,-123.246344);


INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES
(4, 4, 'Lighthouse Labs', 'I loved everything about this program. The teachers and mentors where amazing at breaking concepts down and gave me the confidence to start my career as a developer. The course is definitely a challenge, but one I found exciting and even when I felt stuck there was always someone available to help out. The community around Lighthouse Labs has continued to be a motivating, empowering resource even five years out with their focus on continuing to support alumni education and development. ​If your willing to put in the work Lighthouse Labs is 1000% worth it. decision', 'https://lh5.googleusercontent.com/p/AF1QipO6dJsPyqUDnhPBUr6xxbqzG4h2-7-2Kl9p7mNt=w408-h290-k-no', 49.281220, -123.114774);

INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES
(5, 5, 'Spanish Banks', 'This is going to be one of my most loved locations anywhere. This is a wonderful place to bring the family or even a date. The parking here is free and in the summer there are concessions in a few places down the beach. There are restrooms as well down the beach but at your own discretion but at least there is a restroom.', 'https://lh5.googleusercontent.com/p/AF1QipNsURbXY6CtPdWLrl2_skQWoFXxsYj7LHdL495R=w426-h240-k-no', 49.276836, -123.217490),
(5, 5, 'Locarno Beach', 'Wonderful beach with some picnic tables.  The water in the area though...smelled of feces.  It was nasty.   Cannot imagine taking a dip in it.', 'https://lh5.googleusercontent.com/p/AF1QipOP5A6tEGxRo6junkkUaManpACCCza_U6_vUXIH=w426-h240-k-no', 49.275397, -123.206954),
(5, 5, 'Jericho Beach', 'Pictures say a thousand words', 'https://lh5.googleusercontent.com/p/AF1QipPpjaFtvomXGPOfeg2C0O5IjVRD0crO1-B8lMnB=w408-h271-k-no', 49.272409, -123.194274),
(5, 5, 'Kitsilano Beach', 'View is good. Water is too dirty full of shells. Not recommended if you’re thinking of swimming', 'https://lh5.googleusercontent.com/p/AF1QipPO5ClgwYUsZrlvCLkquwwd0oNOZqQA_o8V8q7I=w408-h271-k-no', 49.274220, -123.154660),
(5, 3, 'Sunset Beach', 'The park area is nice. The beach side is way too small, but good to check the sunset. Too close to the boats passing by, so it has a "dirty" feeling to the water (never got inside in that area).', 'https://lh5.googleusercontent.com/p/AF1QipNvcD4Hf38wK3sjRPEYXpJDwAAvtFTusn1EjPyI=w408-h306-k-no', 49.279144, -123.139175),
(5, 3, 'English Bay', 'My most favourite spot in the city. Daffodils are starting to bloom now and it’s just so beautiful out. It’s a favourite spot for locals to stroll along and bike. The seawall is connected to Stanley Park.  Even on a crisp winter day, you’ll see people walking along with coffees in hand. Just up the block are myriad of eateries and ice cream shops. Grab a lunch to go and bring it down to the beach. ', 'https://lh5.googleusercontent.com/p/AF1QipNz5gVuNB3FF-Klq_xpzxrHboUKULEJSYu7eRe8=w408-h306-k-no', 49.286299, -123.143534),
(5, 1, 'Second Beach', 'Its a bit busy sometimes, but its also really easy to get to.', 'https://lh5.googleusercontent.com/p/AF1QipPzgBX2m8Xa0epmG7IgJoIElYJII2OuZLu1vJca=w408-h272-k-no', 49.294434, -123.150213),
(5, 2, 'Third Beach', 'Similar to the rest of Stanley park. Very scenic, well maintained beach with plenty of room to hang out and have a picnic. Lots of rocks to climb for those more adventurous souls, and the tide comes in high so you can see cool warms and shells when it’s low tide.', 'https://lh5.googleusercontent.com/p/AF1QipNqpBiVx9t-racZfLO3rFaTEl_DYHCy-fToNifz=w408-h306-k-no', 49.304043, -123.156764);


INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES

(7, 4, 'Ramen Gojiro', 'Japanese soups, dumplings, salads & more offered with beer in simple, modern surroundings.', 'https://s3-media0.fl.yelpcdn.com/bphoto/Pw1NHiOT2f4VYsHs3pOCFw/l.jpg', 49.282610, -123.114630),
(7, 4, 'Marutama', 'Japanese place preparing ramen along with gyoza & other dishes in casual, understated surrounds.', 'https://marutama.ca/wp-content/uploads/2016/06/Zenbu-Ramen.jpg', 49.285640, -123.126410),
(7, 4, 'Gyoza Bar', 'Contemporary brick-walled spot for Japanese dumplings, tapas & ramen dishes, with beer, wine & sake.', 'https://gyozabar.ca/wp-content/uploads/2019/08/Ramen-and-Gyoza-Spread.jpg', 49.285640, -123.114853),
(7, 4, 'Kokoro Tokyo Mazesoba', 'Airy, contemporary Japanese eatery serving soupless ramen noodles with creative toppings.', 'https://images.dailyhive.com/20180910124153/Kokoro-Tokyo-Mazesoba.jpg', 49.284649, -123.115310),
(7, 4, 'Jinya Ramen Bar', 'There is a bit of a wait time but the food, ambiance and service is worth it.', 'https://images.dailyhive.com/20170426135512/jinya-ramen-bar.jpg', 49.283420, -123.126411);


INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES

(8, 2, 'Kitsilano Pool', 'This 137-metre, heated saltwater swimming pool on the bay features three slides & a cafe.', 'https://images.glaciermedia.ca/polopoly_fs/1.23796226.1555625718!/fileImage/httpImage/image.jpg_gen/derivatives/landscape_804/kitsilano-pool.jpg', 49.273071, -123.157329),
(8, 2, 'Britannia Pool', 'Great family pool really nice staff. They have saunas inside the change rooms and have a gym right upstairs from the pool.', 'https://www.britanniacentre.org/database/images/DSC_0708.JPG', 49.275654,-123.073787),
(8, 2, 'Second Beach Swimming Pool', 'Big outdoor, heated swimming pool with views of English Bay, kids play features & concessions.', 'https://images.glaciermedia.ca/polopoly_fs/1.22318317.1504218530!/fileImage/httpImage/image.jpg_gen/derivatives/landscape_804/pool.jpg', 49.231229,-123.064989),
(8, 2, 'Templeton Park Pool', 'The pool is a little small, but good swimming instuructors make it worth taking a class there.', 'https://i.cbc.ca/1.4309869.1506537802!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_780/templeton-pool.JPG', 49.2712195, -123.0599196),
(8, 2, 'Renfrew Park Pool', 'This Renfrew pool has great instructors for teaching your kids to swim. They are usually fully booked but their system has recently changed. ', 'https://www.calgary.ca/CSPS/Recreation/PublishingImages/Grid-Banner/Renfrew-grid-1.jpg', 49.2512299,- 123.042891),
(8, 2, 'Killarney Pool', 'Top notch hot tub. Even better steam room. Balcony to cool off is a nice touch. One star for no sauna. Otherwise lovely.', 'https://images.glaciermedia.ca/polopoly_fs/1.23918230.1565991776!/fileImage/httpImage/image.jpg_gen/derivatives/landscape_804/killarney-pool.jpg', 49.2267237,-123.0434269),
(8, 2, 'New Brighton Pool', 'Heated swimming pool open May to September, offering lap lanes, a kids area & harbor views.', 'https://postmediavancouversun2.files.wordpress.com/2019/11/png0522nkitspool-2.jpg', 49.289839, -123.040303),
(8, 2, 'Vancouver Aquatic Centre', 'This place is right by Sunset Beach. You can swim, take swimming lessons for a very good price, ideal for low income families. There is a separate area for smaller children as well.', 'https://s3-media0.fl.yelpcdn.com/bphoto/ZGjL75oidZ3AnQCmRS9fwA/l.jpg', 49.2767503, -123.1353921);


INSERT INTO points (list_id, owner_id, title, description, img_url, latitude, longitude)
VALUES

(9, 3, 'Museum of Vancouver', 'Museum focused on city issues & history, with a strong collection of First Nations art & artifacts.', 'https://img.grouponcdn.com/pwa_test/2Ce5erD6mKzGpiGYEZD3Jy5Fy8Pc/2C-674x418/v1/c700x420.jpg', 49.2763483,-123.1446238),
(9, 3, 'Vancouver Art Gallery', 'Gallery known for its touring exhibits, work by local artists (like Emily Carr) & photo collection.', 'https://images.dailyhive.com/20160809132024/vancouver-art-gallery.jpg', 49.282877, -123.1205639),
(9, 3, 'Science World', 'Interactive science displays & films for kids from toddlers to early teens, inside a geodesic dome.', 'https://www.vmcdn.ca/f/files/via/import/2019/09/05094813_science-world-vancouver.jpg;w=960', 49.2734537, -123.1036739),
(9, 3, 'Gastown Steam Clock', 'Built in 1977, this well-known, antique-style clock is powered by steam & whistles to tell the time.', 'https://s3-media0.fl.yelpcdn.com/bphoto/oB7PnnVgTNR8bevGPVk6hw/o.jpg', 49.192124, -123.171033),
(9, 3, 'VanDusen Botanical Garden', 'Space with ever-changing greenery, flowers & art installations plus fine dining & a casual cafe.', 'https://assets.simpleviewinc.com/simpleview/image/upload/crm/vancouverbc/Heron-Lake-2_B0308D2D-63EF-43CB-95841686D4052681_a284e680-38c3-40bf-adfafbc962a214a1.jpg', 49.239073, -123.134619);
